services:
  spty-web:
    build: .
    container_name: spty-web
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "1404"

    volumes:
      - ./queue.json:/app/queue.json

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M

networks:
  default:
    name: app-network
    external: true